[[plugins]] # ファイルエクスプローラー
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # カーソル位置のコンテキストに合わせてftを切り替える
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # FileTree
repo = 'scrooloose/nerdtree'

[[plugins]] # ColorScheme
repo = 'w0ng/vim-hybrid'

[[plugins]] # snipeet
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # vim git
repo = 'tpope/vim-fugitive'

[[plugins]] # FileExplorer
repo = 'Shougo/denite.nvim'
add_hock="""
call denite#custom#map('insert', "<C-j>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-k>", '<denite:move_to_previous_line>')
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>')
"""

[[plugins]] # formatter
repo = 'Chiel92/vim-autoformat'
add_hock="""
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
"""

[[plugins]] # gitplugin
repo ='Xuyuanp/nerdtree-git-plugin'

[[plugins]] # 変更箇所がわかる
repo ='airblade/vim-gitgutter'

[[plugins]] # ひらがなを認識する
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'

[[plugins]] # 指定範囲を囲む
repo ='tpope/vim-surround'


# Vueを書く環境を作る
[[plugins]]
repo='Shougo/context_filetype.vim'

[[plugins]]
repo='osyo-manga/vim-precious'
# プログラムランナー python用に入れた
[[plugins]]
repo ='thinca/vim-quickrun'

# 複数行コメント
[[plugins]]
repo = 'tomtom/tcomment_vim'
